name: pull-requests
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ Pull Request - Bot }}
          title: "${{ github.event.pull_request.title }}"
          description: ${{ github.event.pull_requests.url }}