name: pull-requests
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Pull Request disponível <br> Título: ${{ github.event.pull_request.title }} <br> - Repositório: ${{ github.event.pull_requests.repo }} <br> - Autor: ${{ github.event.pull_requests.owner }}'